// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACOORCJH0WSWDA5XZzIr1ItKS6izL6fxs',
    appId: '1:763554234599:web:3fcfb2c77313f7a0792242',
    messagingSenderId: '763554234599',
    projectId: 'chat-app-cd8ad',
    authDomain: 'chat-app-cd8ad.firebaseapp.com',
    storageBucket: 'chat-app-cd8ad.appspot.com',
    measurementId: 'G-HVCEPXTVMK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdedbnviPNondIN-Fehm1wQlSdw4Nx934',
    appId: '1:763554234599:android:f32a7fd71d4f5e67792242',
    messagingSenderId: '763554234599',
    projectId: 'chat-app-cd8ad',
    storageBucket: 'chat-app-cd8ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsUvQTdrttD4Nh4JPoGADViIiWhXUKGr0',
    appId: '1:763554234599:ios:5a6206441f3f1c70792242',
    messagingSenderId: '763554234599',
    projectId: 'chat-app-cd8ad',
    storageBucket: 'chat-app-cd8ad.appspot.com',
    iosClientId: '763554234599-33ua2lu32d4rg146dm7bgiqlhpuq0j4p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
